# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/ACAProject/Pipeline/Pipeline.cache/wt [current_project]
set_property parent.project_path D:/ACAProject/Pipeline/Pipeline.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
add_files D:/ACAProject/Pipeline/Pipeline.srcs/sources_1/bd/CPU/CPU.bd
set_property used_in_implementation false [get_files -all D:/ACAProject/Pipeline/Pipeline.srcs/sources_1/bd/CPU/CPU_ooc.xdc]
set_property is_locked true [get_files D:/ACAProject/Pipeline/Pipeline.srcs/sources_1/bd/CPU/CPU.bd]

read_vhdl -library xil_defaultlib {
  D:/ACAProject/Pipeline/Pipeline.srcs/sources_1/new/SignExtender.vhd
  D:/ACAProject/Pipeline/Pipeline.srcs/sources_1/new/RegFile.vhd
  D:/ACAProject/Pipeline/Pipeline.srcs/sources_1/new/InstMem.vhd
  D:/ACAProject/Pipeline/Pipeline.srcs/sources_1/new/IFIDReg.vhd
  D:/ACAProject/Pipeline/Pipeline.srcs/sources_1/new/IDEXReg.vhd
  D:/ACAProject/Pipeline/Pipeline.srcs/sources_1/new/EXMEMReg.vhd
  D:/ACAProject/Pipeline/Pipeline.srcs/sources_1/new/Decoder.vhd
  D:/ACAProject/Pipeline/Pipeline.srcs/sources_1/new/ALU.vhd
  D:/ACAProject/Pipeline/Pipeline.srcs/sources_1/new/DataMem.vhd
  D:/ACAProject/Pipeline/Pipeline.srcs/sources_1/new/PC.vhd
  D:/ACAProject/Pipeline/Pipeline.srcs/sources_1/new/PCAdder.vhd
  D:/ACAProject/Pipeline/Pipeline.srcs/sources_1/new/Mux2to1.vhd
  D:/ACAProject/Pipeline/Pipeline.srcs/sources_1/new/MEMWBReg.vhd
  D:/ACAProject/Pipeline/Pipeline.srcs/sources_1/bd/CPU/hdl/CPU_wrapper.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top CPU_wrapper -part xc7a100tcsg324-3


write_checkpoint -force -noxdef CPU_wrapper.dcp

catch { report_utilization -file CPU_wrapper_utilization_synth.rpt -pb CPU_wrapper_utilization_synth.pb }
