# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/CPU/CPU.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU || ORIG_REF_NAME==CPU}]

# IP: bd/CPU/ip/CPU_SignExtender_0_0/CPU_SignExtender_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_SignExtender_0_0 || ORIG_REF_NAME==CPU_SignExtender_0_0}]

# IP: bd/CPU/ip/CPU_RegFile_0_0/CPU_RegFile_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_RegFile_0_0 || ORIG_REF_NAME==CPU_RegFile_0_0}]

# IP: bd/CPU/ip/CPU_InstMem_0_0/CPU_InstMem_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_InstMem_0_0 || ORIG_REF_NAME==CPU_InstMem_0_0}]

# IP: bd/CPU/ip/CPU_IFIDReg_0_0/CPU_IFIDReg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_IFIDReg_0_0 || ORIG_REF_NAME==CPU_IFIDReg_0_0}]

# IP: bd/CPU/ip/CPU_IDEXReg_0_0/CPU_IDEXReg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_IDEXReg_0_0 || ORIG_REF_NAME==CPU_IDEXReg_0_0}]

# IP: bd/CPU/ip/CPU_EXMEMReg_0_0/CPU_EXMEMReg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_EXMEMReg_0_0 || ORIG_REF_NAME==CPU_EXMEMReg_0_0}]

# IP: bd/CPU/ip/CPU_Decoder_0_0/CPU_Decoder_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_Decoder_0_0 || ORIG_REF_NAME==CPU_Decoder_0_0}]

# IP: bd/CPU/ip/CPU_ALU_0_0/CPU_ALU_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_ALU_0_0 || ORIG_REF_NAME==CPU_ALU_0_0}]

# IP: bd/CPU/ip/CPU_DataMem_0_0/CPU_DataMem_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_DataMem_0_0 || ORIG_REF_NAME==CPU_DataMem_0_0}]

# IP: bd/CPU/ip/CPU_PC_0_0/CPU_PC_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_PC_0_0 || ORIG_REF_NAME==CPU_PC_0_0}]

# IP: bd/CPU/ip/CPU_PCAdder_0_0/CPU_PCAdder_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_PCAdder_0_0 || ORIG_REF_NAME==CPU_PCAdder_0_0}]

# IP: bd/CPU/ip/CPU_Mux2to1_0_1/CPU_Mux2to1_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_Mux2to1_0_1 || ORIG_REF_NAME==CPU_Mux2to1_0_1}]

# IP: bd/CPU/ip/CPU_Mux2to1_1_0/CPU_Mux2to1_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_Mux2to1_1_0 || ORIG_REF_NAME==CPU_Mux2to1_1_0}]

# IP: bd/CPU/ip/CPU_Mux2to1_2_0/CPU_Mux2to1_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_Mux2to1_2_0 || ORIG_REF_NAME==CPU_Mux2to1_2_0}]

# IP: bd/CPU/ip/CPU_MEMWBReg_0_0/CPU_MEMWBReg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_MEMWBReg_0_0 || ORIG_REF_NAME==CPU_MEMWBReg_0_0}]

# IP: bd/CPU/ip/CPU_Mux2to1_3_0/CPU_Mux2to1_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_Mux2to1_3_0 || ORIG_REF_NAME==CPU_Mux2to1_3_0}]

# XDC: bd/CPU/CPU_ooc.xdc
